-- ============================================================
-- SNOWFLAKE ETL + SCD TYPE 2 PIPELINE
-- 01 - CREATE TABLES
-- ============================================================

CREATE OR REPLACE TABLE CUSTOMER_RAW (
    CUSTOMER_ID NUMBER,
    CUSTOMER_NAME VARCHAR,
    CITY VARCHAR,
    LOAD_DATE TIMESTAMP_NTZ,
    SOURCE_FILE VARCHAR
);

CREATE OR REPLACE TABLE CUSTOMER_STG (
    CUSTOMER_ID NUMBER,
    CUSTOMER_NAME VARCHAR,
    CITY VARCHAR,
    LOAD_DATE TIMESTAMP_NTZ,
    SOURCE_FILE VARCHAR
);

CREATE OR REPLACE TABLE CUSTOMER_ERROR (
    CUSTOMER_ID NUMBER,
    CUSTOMER_NAME VARCHAR,
    CITY VARCHAR,
    ERROR_REASON VARCHAR,
    LOAD_DATE TIMESTAMP_NTZ,
    SOURCE_FILE VARCHAR
);

CREATE OR REPLACE TABLE CUSTOMER_DIM (
    CUSTOMER_KEY NUMBER AUTOINCREMENT,
    CUSTOMER_ID NUMBER,
    CUSTOMER_NAME VARCHAR,
    CITY VARCHAR,
    STATE VARCHAR,
    LOAD_DATE TIMESTAMP_NTZ,
    SOURCE_FILE VARCHAR,
    EFFECTIVE_DATE DATE,
    END_DATE DATE,
    IS_CURRENT BOOLEAN
);

CREATE OR REPLACE TABLE CITY_STATE (
    CITY VARCHAR,
    STATE VARCHAR
);
